# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# You should also look at https://theme.hp.gbif-staging.org/documentation-intro for options
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Haupteinstellungen 
title: Biodiversit채tsdatenbank Haus der Natur Salzburg # the title of your site should go here
email: biodiversitaet@hausdernatur.at
description: Biodiversit채tsdatenbank des Haus der Natur Salzburg mit Sammlungs- 
  und Beobachtungsdaten zur regionalen Biodiversit채t.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Biodiversitaetsdatenbank.hausdernatur.at" # the base hostname & protocol for your site, e.g. http://example.com

# Social Media
email: biodiversitaet@hausdernatur.at                                   # Social icon in footer
# twitter_username: yourname # if you have an account you want to link to. Else comment this line out
# github_username:  yourname # if you have an account you want to link to. Else comment this line out
# bluesky_username: yourname.org                            # Social icon in footer
youtube_username: Haus der Natur Salzburg                              # Social icon in footer
facebook_username: Haus der Natur | Salzburg                             # Social icon in footer
# flickr_username: yourname                               # Social icon in footer
instagram_username: hausdernatur                              # Social icon in footer
# mastodon_url: https://something.goes/@here                # Social icon in footer
# linkedin_url: https://www.linkedin.com/company/yourname # Social icon in footer

# Build settings - nicht 채ndern!
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: gbif/jekyll-hp-base-theme

# Design Hosted Portal
BDDB:
  rootLang: de
  latestPostLimit: 3
  logo: /assets/images/placeholders/HdN-Logo-rgb.png  # Logo in navbar, will be displayed with 28px height
  logoAndTitle: true           # include the title next to the logo
  archive_permalink: /news/       # Permalink of page using archive.html layout, required when using post categories
  style:
    square: false               # Should corners be square or rounded
    colors:
      primary: "#4E769F"         # Primary color of your brand. Use HEX code. Used for buttons and links
      links: "#99BB53"          # What color should links have. Use a HEX code. DEfault is primary color. 
    coloredHeadlineLinks: false   # If a headline is a link, then use the link color. Default is true. 
  navbar:                         # RELATED TO NAVIGATION BAR
    # brandBackground: yellow     # Define a custom background for the logo/title in the top navigation bar
    # color: "tomato"             # What color should the navbar be?
    # hasWhiteText: true          # Should the text color be white?
    # floating: true

useSharedLibrary: true # Use the new component library
updateTranslationMenuOnWidgetEvents: true # Notice that this feature requires urls for widgets to be the same across languages (except for a language prefix)

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .LICENSE
  - .netlify.toml
  - serve.json
  - en/data/disabled/
  - README.md
  - /**/README.md  # exclude all README.md files in any folder

permalink: pretty # will strip extensions like .html from urls

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page" # So by default any page will use the layout "page"
      lang: de # And have the default language german
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
      
  - scope:
      path: "en/" # For anything in the "en" folder the default is to set the lang frontMatter property to "en" . this should be deleted or adapted to your site if you support other languages
    values:
      lang: en
  - scope:
      path: "_posts/en" # our subfolder in posts for english translation of news items
    values:
      layout: "post"
      permalink: "/en/post/:year/:slug/"   # Use /en/post/yyyy/{filename}/ as permalink for all posts
      lang: es # And have the default language in that folder be english
  
